### ISSUE TITLE
[BUG] Unnecessary toast that appears on attendee's screen once the organizer starts an election

### ISSUE THREAD

**Issue by Tesa27** [dedis/popstellar#983] opened 2022-05-03 15:29 UTC
When the organizer launches an election, a toast is displayed on attendees screen that states **Could not open the election** but  this does not jeopardize the functionality of the election, the attendee is still able to vote.

**Comment by Warhedgehog** [comment] 2022-06-20 14:15
This was probably caused by #1074, which has been fixed by #1093

**Closed by Warhedgehog** 2022-06-20 14:15 UTC
Labels: bug, fe2-android
